# Generated by Django 5.2.5 on 2025-08-30 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('id_number', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('joined_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('report_tag', models.CharField(blank=True, choices=[('INCOME_INTEREST_ON_LOANS', 'Interest from loans'), ('INCOME_DONATION', 'Donation income'), ('INCOME_LAP_FORMS', 'Income from LAP forms'), ('INCOME_REGISTRATION_FEES', 'Registration fee income'), ('EXP_BANK_CHARGES', 'Bank charges'), ('EXP_MEETING', 'Meeting expenses'), ('EXP_ACCOUNTANCY', 'Accountancy fees'), ('EXP_AGM', 'AGM expenses'), ('EXP_BAD_DEBT_PROVISION', 'Provision for bad debts'), ('EXP_HONORARIA', 'Honoraria'), ('EXP_AUDIT_FEES', 'Audit fees'), ('ASSET_CASH_EQUITY', 'Cash at bank - Equity'), ('ASSET_LOANS_PRINCIPAL', 'Loans receivable - principal'), ('ASSET_LOAN_INTEREST', 'Interest receivable on loans'), ('ASSET_RECEIVABLE_HIGHLANDS', 'Receivable from Highlands Ltd'), ('LIAB_MEMBERS_SAVINGS', 'Total members savings'), ('LIAB_ACCOUNTS_PAYABLE', 'Accounts payable'), ('EQUITY_SHARE_CAPITAL', 'Share capital'), ('EQUITY_RETAINED_EARNINGS', 'Retained earnings'), ('EQUITY_CURRENT_YEAR_SURPLUS', 'Surplus for the year')], max_length=64, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_method', models.CharField(choices=[('REDUCING', 'Reducing balance'), ('FLAT', 'Flat')], default='REDUCING', max_length=16)),
                ('disbursed_on', models.DateField()),
                ('tenor_months', models.PositiveIntegerField()),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.journalentry')),
            ],
            options={
                'indexes': [models.Index(fields=['account'], name='core_journa_account_04bec6_idx'), models.Index(fields=['entry', 'account'], name='core_journa_entry_i_1525e4_idx')],
            },
        ),
    ]
