# Generated by Django 5.2.5 on 2025-08-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payroll_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
