# Generated by Django 5.2.5 on 2025-08-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingstransaction',
            name='source',
            field=models.CharField(blank=True, help_text="Optional tag for transaction origin (e.g. 'Loan Overpayment', 'Mobile Deposit', 'Manual Entry')", max_length=50),
        ),
    ]
