# Generated by Django 5.2.5 on 2025-08-30 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_method', models.CharField(choices=[('REDUCING', 'Reducing balance'), ('FLAT', 'Flat')], default='REDUCING', max_length=16)),
                ('default_tenor_months', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_method', models.CharField(choices=[('REDUCING', 'Reducing balance'), ('FLAT', 'Flat')], max_length=16)),
                ('disbursed_on', models.DateField()),
                ('tenor_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('interest_account', models.ForeignKey(limit_choices_to={'report_tag': 'ASSET_LOAN_INTEREST'}, on_delete=django.db.models.deletion.PROTECT, related_name='loan_interest_account', to='core.account')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member')),
                ('principal_account', models.ForeignKey(limit_choices_to={'report_tag': 'ASSET_LOANS_PRINCIPAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='loan_principal_account', to='core.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=14)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='loans.loan')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('loan', 'installment_no')},
            },
        ),
    ]
