# Generated by Django 5.2.5 on 2025-08-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='excess_routed_to_savings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount from this repayment that was redirected to savings', max_digits=14),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='source',
            field=models.CharField(blank=True, help_text="Optional tag for repayment origin (e.g. 'Mobile', 'Manual', 'Auto')", max_length=50),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_method',
            field=models.CharField(choices=[('REDUCING', 'Reducing balance'), ('FLAT', 'Flat')], max_length=16),
        ),
    ]
